[font]
size = 11

[font.bold]
family = "jetbrainsmono nerd font"
style = "Bold"

[font.italic]
family = "jetbrainsmono nerd font"
style = "Regular"

[font.bold_italic]
family = "jetbrainsmono nerd font"
style = "Regular"

[font.normal]
family = "jetbrainsmono nerd font"
style = "Regular"

[window]
opacity = 0.9
